include: [".well-known"]

defaults:
  - scope:
      path: ".well-known/matrix"
    values:
      custom_headers:
        - key: "Content-Type"
          value: "application/json"
        - key: "Access-Control-Allow-Origin"
          value: "*"
